### ISSUE TITLE
Restore Helper Issue

### ISSUE THREAD

**Issue by davidkflau** [abinav2307/azure-cosmosdb-custom-pointInTimeRestore#11]
I saw when performing the restore, there is a restore helper document created in a cosmos db collection. The key of this document is the blob storage backup container name. The purpose of doing this is to prevent another instance from restoring the same container at the same time. However, after the restoring, the document is not deleted so when I restore the same backup container next time, it can't create another new restore helper as the id is the same as the previous one, which results in failing to restore.

Question:
Do you assume the user needs to delete the restore helper document every time after restoring in order to restore the same backup container next time? Or is it better to add a "lock" status and release the lock after restoring?

@abinav2307

**Comment by abinav2307** [comment]
@davidkflau yes if the restore job is being run for a second time, ideally the entire RestoreHelper container should be deleted and the restore job will execute to restore all the documents into the new container the data is being restored to for a second time. Let me know if this helps.
