### ISSUE TITLE
Packages folder included on the repo

### ISSUE THREAD

**Issue by mambru** [abinav2307/azure-cosmosdb-custom-pointInTimeRestore#6]
The nuget package is included into the repo, this is not usually the best option. If there is not real reason for these files to be there, I can work on a PR adding the exclusion to the gitignore and removing the contents from the repo.

**Comment by abinav2307** [comment]
@mambru, the reason we chose to do this, although unconventional, is to allow users to simply pull down the entire repo, build locally and push to the execution platform of their choice (App Service, Virtual Machine Scale Sets etc.) without even having to do a restore of Nuget packages. The goal was to make it as hands off as possible, hence the unconventional approach :)
